### PR TITLE
Adding QI Validation

### PR DESCRIPTION
**Pull request by IsmailM**
@yeban, Can you take a look.

Many Thanks,
IsmailM

### CODE REVIEW

**Comment by yeban** [comment]
The QI column lists splice sites first and exons second. If possible, it would be better to reverse the order.

QI column says 'unexpected error' for the following defline: '>AP201408-maker-Si_gnH.scaffold00108-augustus-gene-0.11-mRNA-1 protein AED:0.05 eAED:0.07 QI:0|0.66|0.7|1|0.66|0.6|10|1423|831'

**Comment by yeban** [comment]
I must note that for that sequence, other validations didn't return anything either (Not enough evidence). Just in case this is related. Here's the full test case:

```
>AP201408-maker-Si_gnH.scaffold00108-augustus-gene-0.11-mRNA-1 protein AED:0.05 eAED:0.07 QI:0|0.66|0.7|1|0.66|0.6|10|1423|831
MRYVLNDIFFSTARPQKVAQDLYDEMSSLREKIIAAGGKDPGKIEEPRLPQVEWPKQSPP
```

**Comment by IsmailM** [comment]
I don’t have an issue with that sequence (I’m using SwissProt)…

The only thing I can think of is that there are not enough BLAST hits, which results in the ‘not enough evidence’ error. Nevertheless, I have no removed the hits assertion for the maker QI validation and so that should fix the issue (if that was indeed the issue).

**Comment by yeban** [comment]
That probably was the problem ... working for me now.

**Pull request merged**
