### PR TITLE
Alpha

### PR DESCRIPTION
**Pull request by IsmailM**
- move the modals to just below the body tag - this means that they are still available if someone stops the analysis before the footer is printed...
- Rename gem spec file (GeneValidator.gemspec to genevalidator.gemspec) so that 'rake' works 
- Have a maximum of 5000 rows per results file... (This number is editable by changing this single variable [here](https://github.com/wurmlab/genevalidator/blob/alpha/lib/genevalidator.rb#L48))...

### CODE REVIEW

**Comment by yeban** [comment]
I'm not sure I understand the intent here. Are you splitting the results across several HTML files, each reporting 5000 sequences?

**Comment by IsmailM** [comment]
Yep, that's the idea....

Currently, if someone is analysing a large input file, GV produces a single large output html file. This output file can be large enough to crash the browser...

Thus as temporary solution, it was felt that it would be better to split the output file into multiple smaller files...

**Comment by yeban** [comment]
Very 90s, but ok. Do you add links to all generated HTML page to each page? Like, http://getbootstrap.com/components/#pagination. Couldn't be sure from the diff.

**Comment by IsmailM** [comment]
Yep I agree, this isn't the perfect solution... It is hoped that this is only a temporary solution (it is better than what we currently have - which simply crashes the browser)...

The HTML don't have paginations - this was because the files are made up of table of 5000 rows (and so it was felt that paginations wouldn't really make life easier for the user).

Hopefully my next PR (possibly coming tomorrow) will lead the way for a better solution...

**Comment by IsmailM** [comment]
Just added Pagination...

Will be merging with master shortly...

**Pull request merged**
