### PR TITLE
Alpha

### PR DESCRIPTION
**Pull request by IsmailM**
- Removes outdated documentation - this was really old;
- Adds `-e --extract_raw_seqs` command line argument
- Adds Json 
- Remove YAML - the current yaml was made up ruby objects and so could not really be used outside ruby and GV  (if it is necessary to have YAML, we can easily change the JSON to yaml )
- General refactoring

@yeban, if you get a chance, do you mind having a quick look - perhaps test it on a few input files...

### CODE REVIEW

**Comment by yeban** [comment]
I am running this on 5000 sequences. Will get back to you when it's done.

**Comment by yeban** [comment]
Overall GV felt responsiveness today. The code is much readable now. I miss the sticky table header from the initial versions.

I killed GV after running it for around 6 hours in which time it processed ~4k proteins at 8 threads. Memory usage is extremely high. On my iMac, after processing first few 100 sequences, GV was constantly hogging 7.5 / 8 GB of RAM and around 3-4GB of what OSX shows as "compressed" memory. I also noticed memory usage of MAFFT can grow to as much as 50GB when aligning 500 hits. Sometimes a single MAFFT process can take very long to run (e.g.: MAFFT was stuck on a ~2300th sequence while GV, working parallely, was already processing ~3300th sequence).

The index.html (results.html) generated by GV is around 22MB. It loaded fully in Chrome in ~5 seconds. Opening all plots for a sequence (one sequence at a time) was snappy enough. Did this for ~20 sequences without any performance degradation. But this big index.html file is frankly an alien concept to me and if the size of index.html grows linearly ... it's not good.

I ran GV and viewed results on my iMac which has a quad core 3.2 GHz processor with hyper threading, turbo boosting and all; 8GB of RAM; 1GB graphics card, and I enable experimental optimisations in Chrome from time to time.

**Comment by yeban** [comment]
Safari hasn't rendered anything in the 5 mins it took me to write the previous comment.

**Comment by yeban** [comment]
Firefox loads in under 5s. But opening plots for sequences (one by one) isn't as snappy as it was in Chrome. Scrolling becomes slow in Firefox when the plots are being rendered and then resumes normally.

**Comment by IsmailM** [comment]
Thanks @yeban,

I'll now push this into the master...

@yeban, I would highly appreciate it if you could make the input and output files available on prometheus or sm11 - this will save me the time from blasting another large input file myself...

**Pull request merged**
