### PR TITLE
yeban/rake

### PR DESCRIPTION
**Pull request by yeban**
Alternative to #86. Takes a pragmatic approach to Rakefile. Includes @IsmailM's yard commit from #86. Addresses @monicadragan's issue (due to codeclimate-test-reporter gem not in deps list).

### CODE REVIEW

**Comment by yannickwurm** [comment]
thanks for proposing this @yeban - this indeed seems like a more robust solution

**Comment by monicadragan** [comment]
Sorry, but this doesn't work even if I install codeclimate-test-reporter gem by hand -- unless I remove the tests dependency.
On Prometheus 'rake' doesn't work neither.

**Comment by yeban** [comment]
Post me a stack trace ... or something else to debug the issue. I just cloned gv in a pristine env on prometheus (only ruby installed from before) and ran rake - all tests pass. Also ran gv on the bundled protein data - worked.

**Comment by monicadragan** [comment]
Hi, thanks for inspecting this! The error is the same as before.

$ gem list
*** LOCAL GEMS ***
activesupport (4.2.1)
awesome_print (1.6.1)
bigdecimal (1.2.0)
bio (1.4.3.0001)
bio-blastxmlparser (2.0.2, 1.1.2)
bio-logger (1.0.1)
clbustos-rtf (0.4.2)
codeclimate-test-reporter (0.4.7)

$ sudo rake install
sudo: unable to resolve host work
/usr/local/bin/ruby -I"lib:lib" -I"/usr/local/lib/ruby/2.0.0" "/usr/local/lib/ruby/2.0.0/rake/rake_test_loader.rb" "test/test_all_validations.rb" "test/test_blast.rb" "test/test_clusterization.rb" "test/test_clusterization_2d.rb" "test/test_extended_array_methods.rb" "test/test_helper.rb" "test/test_sequences.rb" "test/test_validation_open_reading_frame.rb" "test/test_validations.rb" 
I, [2015-07-16T19:53:26.213665 #31384]  INFO -- : Not reporting to Code Climate because ENV['CODECLIMATE_REPO_TOKEN'] is not set.
/usr/local/lib/ruby/2.0.0/rake/ext/module.rb:36:in `const_missing': uninitialized constant MiniTest::Test (NameError)
	from /usr/local/lib/ruby/2.0.0/minitest/unit.rb:28:in `const_missing'
	from /home/monique/genevalidator/test/test_all_validations.rb:9:in `<module:GeneValidator>'
	from /home/monique/genevalidator/test/test_all_validations.rb:7:in `<top (required)>'
	from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from /usr/local/lib/ruby/2.0.0/rake/rake_test_loader.rb:15:in `block in <main>'
	from /usr/local/lib/ruby/2.0.0/rake/rake_test_loader.rb:4:in `select'
	from /usr/local/lib/ruby/2.0.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:lib" -I"/usr/local/lib/ruby/2.0.0" "/usr/local/lib/ruby/2.0.0/rake/rake_test_loader.rb" "test/test_all_validations.rb" "test/test_blast.rb" "test/test_clusterization.rb" "test/test_clusterization_2d.rb" "test/test_extended_array_methods.rb" "test/test_helper.rb" "test/test_sequences.rb" "test/test_validation_open_reading_frame.rb" "test/test_validations.rb" ]

Tasks: TOP => install => build => test
(See full trace by running task with --trace)

**Comment by IsmailM** [comment]
Hey Guys,

Just submitted this PR…

I have tested running rake on a clean system…

Kind Regards,  
Ismail M
Sent with Airmail

On 16 July 2015 at 18:51:40, Monica Dragan (notifications@github.com) wrote:

Hi, thanks for inspecting this! The error is the same as before.

$ gem list
*** LOCAL GEMS ***
activesupport (4.2.1)
awesome_print (1.6.1)
bigdecimal (1.2.0)
bio (1.4.3.0001)
bio-blastxmlparser (2.0.2, 1.1.2)
bio-logger (1.0.1)
clbustos-rtf (0.4.2)
codeclimate-test-reporter (0.4.7)

$ sudo rake install
sudo: unable to resolve host work
/usr/local/bin/ruby -I"lib:lib" -I"/usr/local/lib/ruby/2.0.0" "/usr/local/lib/ruby/2.0.0/rake/rake_test_loader.rb" "test/test_all_validations.rb" "test/test_blast.rb" "test/test_clusterization.rb" "test/test_clusterization_2d.rb" "test/test_extended_array_methods.rb" "test/test_helper.rb" "test/test_sequences.rb" "test/test_validation_open_reading_frame.rb" "test/test_validations.rb"
I, [2015-07-16T19:53:26.213665 #31384] INFO -- : Not reporting to Code Climate because ENV['CODECLIMATE_REPO_TOKEN'] is not set.
/usr/local/lib/ruby/2.0.0/rake/ext/module.rb:36:in const_missing': uninitialized constant MiniTest::Test (NameError)
from /usr/local/lib/ruby/2.0.0/minitest/unit.rb:28:inconst_missing'
from /home/monique/genevalidator/test/test_all_validations.rb:9:in <module:GeneValidator>'
from /home/monique/genevalidator/test/test_all_validations.rb:7:in'
from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in require'
from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:inrequire'
from /usr/local/lib/ruby/2.0.0/rake/rake_test_loader.rb:15:in block in <main>'
from /usr/local/lib/ruby/2.0.0/rake/rake_test_loader.rb:4:inselect'
from /usr/local/lib/ruby/2.0.0/rake/rake_test_loader.rb:4:in `

'
rake aborted!
Command failed with status (1): [ruby -I"lib:lib" -I"/usr/local/lib/ruby/2.0.0" "/usr/local/lib/ruby/2.0.0/rake/rake_test_loader.rb" "test/test_all_validations.rb" "test/test_blast.rb" "test/test_clusterization.rb" "test/test_clusterization_2d.rb" "test/test_extended_array_methods.rb" "test/test_helper.rb" "test/test_sequences.rb" "test/test_validation_open_reading_frame.rb" "test/test_validations.rb" ]
Tasks: TOP => install => build => test
(See full trace by running task with --trace)

**Pull request merged**
